meta:
  url: https://gabelluardo.github.io/workshop-11-nov
  title: workshop-11-nov
  description:
  siteName:
slide:
  loop: false
  targetBlank: true
  ui:
    sidebar: false
    pagination: bullets
    effect:
  code:
    theme: okaidia
